### ISSUE TITLE
utf8clip requires .NET Core 3.0 runtime, won't work on 3.1 or later

### ISSUE THREAD

**Issue by WaterSibilantFalling** [bluemarsh/utf8clip#1]
```
PS C:\windows\system32> dotnet tool install --global utf8clip
error NU1202: Package utf8clip 1.0.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any. Package utf8clip 1.0.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
The tool package could not be restored.
Tool 'utf8clip' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

**Comment by WaterSibilantFalling** [comment]
I then installed by hand, downloaded the *.zip, and when I ran it I got:

```
PS C:\sdm_bin> .\utf8clip.exe
It was not possible to find any compatible framework version
The specified framework 'Microsoft.WindowsDesktop.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download

```

**Comment by aaron-meyers** [comment]
Thanks for trying it out! As mentioned in the README, this utility requires the .NET Core 3.0 runtime as it depends on WPF assemblies that were introduced in .NET Core 3.0. Windows Clipboard support isn't provided in .NET Core 2.1 or earlier.

You can check which runtimes you have installed by running `dotnet --list-runtimes`. You'll need to install the .NET Core 3.0 runtime if it isn't listed there (you should see entries for both Microsoft.NETCore.App 3.0.x and Microsoft.WindowsDesktop.App 3.0.x).

It should however in theory work with .NET Core 3.1 or later as well, but I just tried it on a machine that only has .NET Core 3.1 and it isn't working. So I'll keep this issue open until I fix that.

**Comment by aaron-meyers** [comment]
Actually, it is working just fine on .NET Core 3.1 after all. I wasn't paying attention to the fact that the string currently on my clipboard was '.NET Core 3.0 runtime is required.' and mistook this for output from .NET itself 😅
